### ISSUE TITLE
Problem with the script

### ISSUE THREAD

**Issue by Ferks-FK** [SanjaySRocks/OGP-Installer#1]
### Problem
In the useful step of the script, where you should probably display the database information to continue installing the panel, the following errors:

`cat: /root/ogp_user_password: No such file or directory`
`bash: cd: /root/ogp_panel_mysql_info: Not a directory`

### Expected outcome
Should probably display all the information in the database to continue the configuration on the panel.

### How to reproduce the error
Just follow the entire script process, in the end the error will happen.

### Operating system/browser used
Linux Ubuntu 18.04 and Google Chrome

**Comment by SanjaySRocks** [comment]
did you use the root user for installing the script?

**Comment by SanjaySRocks** [comment]
script updated
